import type { Permission } from "../domain/model.js";
// Platform permission needed by the bootstrap operation query; no grant is implied.
export const permissions: readonly Permission[] = [
  { code: "asset.create", resource_type: "asset", action: "create" },
  {
    code: "asset.lifecycle.change",
    resource_type: "asset",
    action: "lifecycle.change",
  },
  { code: "asset.retire", resource_type: "asset", action: "retire" },
  { code: "asset.receive", resource_type: "asset", action: "receive" },
  { code: "asset.reserve", resource_type: "asset", action: "reserve" },
  { code: "asset.assign", resource_type: "asset", action: "assign" },
  { code: "asset.transfer", resource_type: "asset", action: "transfer" },
  {
    code: "asset.request_return",
    resource_type: "asset",
    action: "request_return",
  },
  {
    code: "asset.receive_return",
    resource_type: "asset",
    action: "receive_return",
  },
  { code: "ticket.create", resource_type: "ticket", action: "create" },
  { code: "ticket.assign", resource_type: "ticket", action: "assign" },
  { code: "ticket.update", resource_type: "ticket", action: "update" },
  { code: "ticket.resolve", resource_type: "ticket", action: "resolve" },
  { code: "ticket.reopen", resource_type: "ticket", action: "reopen" },
  { code: "work_item.resolve", resource_type: "work_item", action: "resolve" },
  {
    code: "monitoring.event.write",
    resource_type: "monitoring_event",
    action: "write",
  },
  { code: "session.revoke", resource_type: "session", action: "revoke" },
  {
    code: "authorization.evaluate",
    resource_type: "authorization",
    action: "evaluate",
  },
  { code: "operation.read", resource_type: "operation", action: "read" },
  { code: "user.read", resource_type: "user", action: "read" },
  { code: "role_binding.read", resource_type: "role_binding", action: "read" },
  { code: "rbac.manage", resource_type: "rbac", action: "manage" },
  { code: "agent.enroll", resource_type: "agent", action: "enroll" },
  { code: "incident.create", resource_type: "incident", action: "create" },
  { code: "incident.update", resource_type: "incident", action: "update" },
  {
    code: "incident.correlate",
    resource_type: "incident",
    action: "correlate",
  },
  {
    code: "incident.declare_major",
    resource_type: "incident",
    action: "declare_major",
  },
  {
    code: "incident.communicate",
    resource_type: "incident",
    action: "communicate",
  },
  { code: "sla.manage", resource_type: "sla", action: "manage" },
  { code: "approval.create", resource_type: "approval", action: "create" },
  { code: "approval.decide", resource_type: "approval", action: "decide" },
  { code: "problem.manage", resource_type: "problem", action: "manage" },
  { code: "change.manage", resource_type: "change", action: "manage" },
  { code: "knowledge.manage", resource_type: "knowledge", action: "manage" },
];
