ALTER TABLE operations.work_items DROP CONSTRAINT work_items_source_type_check;
ALTER TABLE operations.work_items ADD CONSTRAINT work_items_source_type_check CHECK (source_type IN (
  'TICKET','INCIDENT','APPROVAL','NETWORK_EXCEPTION','OFFBOARDING','SOFTWARE_EXCEPTION',
  'ASSET_LIFECYCLE','GOODS_RECEIPT','INVOICE_DUPLICATE','INVOICE_MATCH_EXCEPTION',
  'CONTRACT','RENEWAL','COMMERCIAL_DOCUMENT','CONTRACT_ALERT','COST_PROVENANCE',
  'AUTOMATION_CONFLICT','AUTOMATION_REVIEW','AUTOMATION_EXECUTION','CORRELATION_REVIEW',
  'ASSET_RISK_REVIEW'
));

CREATE UNIQUE INDEX work_items_one_open_asset_risk_review
  ON operations.work_items(tenant_id,(context_json->>'asset_id'))
  WHERE source_type='ASSET_RISK_REVIEW' AND state NOT IN ('RESOLVED','CLOSED');
