export {
  createSoftwareProduct,
  readSoftwareProductReference,
  createSoftwareVersion,
  assertVersionAcceptsArtifact,
  changeSoftwareClassification,
  updateSoftwareVisibility,
  publishSoftwareVersion,
  listSoftwareProducts,
  listSoftwareVersions,
  withdrawPublishedArtifact,
} from "./application/catalog.js";
export {
  createDeploymentCampaign,
  transitionDeploymentCampaign,
  listDeploymentCampaigns,
  readDeploymentCampaign,
  listDeploymentTargets,
  retryDeploymentTarget,
  nextDeploymentCandidate,
  claimDeploymentTarget,
  reportDeploymentResult,
  type DeploymentReport,
} from "./application/deployments.js";
export {
  normalizeSoftwareName,
  ingestSoftwareInventory,
  createProductAlias,
  createUninstallProfile,
  approveUninstallProfile,
  listSoftwareInventory,
  listSoftwareExceptions,
  readSoftwareException,
  requestExceptionApproval,
  approveTemporaryException,
  markFalsePositive,
  ignoreExceptionByPolicy,
  requestExceptionInvestigation,
  requestExceptionRemoval,
  claimRemovalJob,
  reportRemovalResult,
  getExceptionRemovalJob,
  inspectExceptionForReview,
  type SoftwareInventoryItem,
} from "./application/inventory-exceptions.js";
export const permissions = [
  { code: "software.read", resource_type: "software_product", action: "read" },
  {
    code: "software.catalog.manage",
    resource_type: "software_product",
    action: "manage",
  },
  {
    code: "software.deploy",
    resource_type: "software_deployment",
    action: "create",
  },
  {
    code: "software.deployment.read",
    resource_type: "software_deployment",
    action: "read",
  },
  {
    code: "software.deployment.cancel",
    resource_type: "software_deployment",
    action: "cancel",
  },
  {
    code: "software.retry_deployment",
    resource_type: "software_deployment",
    action: "retry",
  },
  {
    code: "software.inventory.read",
    resource_type: "software_inventory",
    action: "read",
  },
  {
    code: "software.exception.read",
    resource_type: "software_exception",
    action: "read",
  },
  {
    code: "software.exception.manage",
    resource_type: "software_exception",
    action: "manage",
  },
  {
    code: "software.exception.approve",
    resource_type: "software_exception",
    action: "approve",
  },
  {
    code: "software.removal.manage",
    resource_type: "software_removal",
    action: "manage",
  },
] as const;
